name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/default_workouts?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
          -I
